                                                     

                                     
                                  
                          
 

                                    
                      
                 
                   
                                                            
                  
                                 
 

                                
                                      
                         
                                                                       
                                        
 

                              
                         
                                                      
                                  
 

                               
              
                            
                  
 

                               
                  
                                              
 

                                
                                                                     
                    
                                                      
                  
                    
                          
                            
                                          
 

/**
 * Every gateway implements this. Adding one is a new file plus a registry entry —
 * the same adapter pattern used for storage, notifications and printing.
 */
                                  
              
                                                                        
                    
                                                                         
                           

                                                                                            
                                                                               
                                                                                        
 
