                                       

/** Semantic status. Independent of the brand accent on purpose. */
                                                             

export const toneVars = (tone       = "info") => ({
  fg: `var(--tone-${tone})`,
  wash: `var(--tone-${tone}-wash)`,
});

                                     
                      
                     
                       
 

                             
                      
              
 

                            
                      
                     
                                                                     
                                                                           
                      
                        
 

                             
                
                       
              
 

                             
                
                   
              
 

                                
              
                
                 
 

                                  
               
                
 

                                 
                                            
 

                                   
                
               
               
                                                
                     
 

                             
                
                       
                       
 

                               
                
                       
 

                     
            
            
 

                                 
              
 

                                
                                                
 

                                
                
                    
 
